version: '3.8'

services:
  kevinstamp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # MailChannels configuration
      - MAILCHANNELS_API_KEY=${MAILCHANNELS_API_KEY}
      # Cloudflare KV configuration (for production deployment)
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_KV_NAMESPACE_ID=${CLOUDFLARE_KV_NAMESPACE_ID}
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      # Application configuration
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-enquiries@stampchain.io}
    volumes:
      # Development volume mounts for hot reload
      - ./server:/app/server:ro
      - ./client:/app/client:ro
      - ./shared:/app/shared:ro
      - ./attached_assets:/app/attached_assets:ro
    networks:
      - kevinstamp-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Redis service for development caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - kevinstamp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  kevinstamp-network:
    driver: bridge

volumes:
  redis-data:
    driver: local